name: Enlightened Warriors
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99513
title: Enlightened Warriors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7d8c3'
    - '#635036'
    - '#f38924'
    - '#00ceff'
    - '#007098'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
